//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUpdateTrancation
    {
        public string BBL { get; set; }
        public short IsInsert { get; set; }
        public short IsDelete { get; set; }
        public short IsUpdate { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public System.DateTime DateTimeProcessed { get; set; }
        public string IdentifyingColumnName { get; set; }
        public string TableName { get; set; }
    }
}
